CREATE TABLE IF NOT EXISTS drone (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    serial_number VARCHAR(64) NOT NULL UNIQUE,
    model VARCHAR(64) NOT NULL,
    weight DECIMAL(10,2) NOT NULL,
    max_height INTEGER NOT NULL,
    max_speed INTEGER NOT NULL,
    battery_capacity INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);